name: Build and Push Image

on:
  push:
    tags:
    - "*"

jobs:
  build-and-publish:
    name: Build and Push docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
        project_id: master-test-409516

    - name: Configure docker for artifact registry
      run: |
        gcloud auth configure-docker asia-northeast2-docker.pkg.dev

    - name: set TAG
      run: |
        echo "TAG=$(echo $GITHUB_REF | awk -F/ '{print $NF}')" >> $GITHUB_ENV

    - name: Build
      run: |
        docker build -t asia-northeast2-docker.pkg.dev/master-test-409516/ar-test/example:${{ env.TAG }} ./

    - name: Push
      run: |
        docker push asia-northeast2-docker.pkg.dev/master-test-409516/ar-test/example:${{ env.TAG }}
