name: Build and Push Image

on:
  push:
    tags:
    - "*"

jobs:
  build-and-publish:
    name: Build and Push docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}

    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure docker for artifact registry
      run: |
        gcloud auth configure-docker asia-northeast2-docker.pkg.dev

    - name: set TAG
      run: |
        echo "TAG=$(echo $GITHUB_REF | awk -F/ '{print $NF}')" >> $GITHUB_ENV

    - name: Build
      run: |
        docker build -t asia-northeast2-docker.pkg.dev/master-test-409516/ar-test/cloud-run-demo:${{ env.TAG }} ./

    - name: Push
      run: |
        docker push asia-northeast2-docker.pkg.dev/master-test-409516/ar-test/cloud-run-demo:${{ env.TAG }}
    
    - name: Deploy
      run: |
        gcloud run deploy cloud-run-demo --region=asia-northeast2 --image=asia-northeast2-docker.pkg.dev/master-test-409516/ar-test/cloud-run-demo:${{ env.TAG }} --platform=managed --project=master-test-409516
